### ISSUE TITLE
Functioning of app between different devices

### ISSUE THREAD

**Issue by xaldoale** [philiiiiiipp/Android-Screen-to-Face-Distance-Measurement#1]
Hi Philipp,

I compiled the code and I am testing the app with different Android devices.
What can you say about the precision of the measurements? I am not obtaining good distance calculation. I read in your paper that the range is "19cm to 94cm with a maximum deviation of 2.1cm".

I see in your youtube video that the measurements are very fast and reactive, what were the frame per second that you set?
In the video you use an iPhone, right? I am using a Moto G and the measurements are not so good!

What kind of indication can you give me? Is it necessary to managing some settings? Or other?

Thanks

Regards,
Alessandro

**Comment by philiiiiiipp** [comment]
Hey Alessandro,

cool that you are checking it out. In my video I am filming with an iPhone,
but I am using a one plus one (http://oneplus.net/one).

I think you might use a camera resolution which is too high? The higher the
resolution the slower the calculation.
Have a look at MainActivity.java line 90, I am trying to get a good
resolution there but it might be that it is too high for your device. I
guess you might get good results in the 400x300 range.

What are you trying to do with it ?

All best
Philipp

**Comment by xaldoale** [comment]
Hi Philipp,

I add you in skype, my account is xaldoale.
I would like to discuss with you the code of Android Screen Distance.

Are you available?

Thanks.

Best,
Alessandro

Il mercoledì 5 novembre 2014, Philipp Beau <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> ha scritto:
