### ISSUE TITLE
About Calibration

### ISSUE THREAD

**Issue by ZhuFengdaaa** [philiiiiiipp/Android-Screen-to-Face-Distance-Measurement#2]
The app is wonderful，It's amazing and I like it.
1. As new user, can author how to Calibrate it? I tried to press the "calibrate" button and touch the phone screen, but nothing happened.
2. the measured distance showed it a bit more farther than the real distance. I don't know what cause it? maybe the light? or something else?

**Comment by philiiiiiipp** [comment]
Hey,

cool that you like it :-).

You should hold your head one dinA4 paper length away. Best ist to roll a
paper and use it as a distance measuring device. I think this might have
been very unclear in my explanation. I will add some more about that when I
have the time. Thanks for giving me feedback!

Best
Philipp

**Comment by ZhuFengdaaa** [comment]
Thanks for your patience. Now I now a little more about Calibration. It looks more precise.
Maybe we can discuss how to measure the result more precise ?

Best
Zhu

**Comment by philiiiiiipp** [comment]
Sure. If you want to improve it, go ahead

Best
Philipp

**Comment by ZhuFengdaaa** [comment]
I have a question, that why you put the **height and width definition of < com.tec.fontsize.CameraSurfaceView > box** in mainActivity rather than measurement_activity.xml ?

**Comment by ZhuFengdaaa** [comment]
Is the CamerasurfaceView.java in your project same as here [Google code](https://searchcode.com/codesearch/view/39145617/)?  Or you just create by yourself?

**Comment by philiiiiiipp** [comment]
Hey,
1. I think I wanted the view size to be variable if there is a different
   phone, so it always uses 95% and 60% of the display. Those numbers where
   chosen because they fitted my test devices, but I am sure there are smarter
   ways to do this.
2. I think the initial class comes from the Google site as far as I
   remember.

All the best
Philipp
