### ISSUE TITLE
request to send a copy of ieee paper

### ISSUE THREAD

**Issue by Nimisha-V-Arun** [philiiiiiipp/Android-Screen-to-Face-Distance-Measurement#5]
Hello Philip,

This is Nimisha:), i am pursuing my undergraduation  in the field of computer engineering, here in India.
I am new to computers , and still in the learning process. Please help me out in understanding your code . 
Can  you also send me a copy of the ieee paper on the " Android-Screen to face distance measurement"?
I really need your help . 
I look forward to hearing from you. 
:-)

Thank you .

**Comment by philiiiiiipp** [comment]
Hey Nimisha,

sure, if you send me your email I will send you a copy.

**Comment by Nimisha-V-Arun** [comment]
This is my email address
v.animisha1@gmail.com
