### ISSUE TITLE
No access to IEEE

### ISSUE THREAD

**Issue by ReginaNg96** [philiiiiiipp/Android-Screen-to-Face-Distance-Measurement#7]
Sorry that i have to contact you through this way. Can I have a complete document of your analysis as I am unable to view the full text after trials. Your help will be fully appreciated. Thank you so much and I hope to hear from you soon.

**Comment by philiiiiiipp** [comment]
Hey, 

I think I should have added a link in the readme a long time ago. 

https://github.com/philiiiiiipp/Android-Screen-to-Face-Distance-Measurement/blob/master/A%20new%20context%20-%20Screen%20to%20Face%20distance%201%201.pdf

**Comment by ReginaNg96** [comment]
Hi Phillip, 

Thankyou so much for your reply. Your project is helping me so much but I have some struggle in calling the distance to respond to certain functions. Like when the distance is lesser than 10cm, the phone screen should blur. 

Wanna ask will you mind to have a look at my project too. Your help will be fully appreciated. Thank you. Looking forward for your reply. 

Regards,
Regina Ng

**Comment by philiiiiiipp** [comment]
Hey Regina,

Thats so nice to hear 😊.

You might want to try a lower resolution, as you can see in the paper back then the face detection stopped working at certain distances which was earlier for higher resolutions.

I am not really knowledgeable in android anymore so you will have to figure this one out by yourself.
