### ISSUE TITLE
two questions regarding your implementation

### ISSUE THREAD

**Issue by matanel-6over6** [philiiiiiipp/Android-Screen-to-Face-Distance-Measurement#8]
1. Why did you used with CALIBRATION_DISTANCE_A4_MM?
2. I checked your app but its not accurate. i get 30 mm instated of 60 mm

10x for your help

**Comment by philiiiiiipp** [comment]
1. Its the length of a standard a4 piece of paper.
2. Might very well be. This code is unmaintained since a couple of years and I am not sure whether it still works on current versions of android.

**Comment by matanel-6over6** [comment]
10x that you answered quickly.
1. But why you checked this?
2. I fixed the gradle and its running but its not accurate

Do you know how can i get the distance from eyes to camera (front camera) with Arcore or with another way?

**Comment by philiiiiiipp** [comment]
1. You can read about it here https://github.com/philiiiiiipp/Android-Screen-to-Face-Distance-Measurement/blob/master/README.md

Not really, like I said I havent really worked on this for years.
